main = "index.html"

[build]
command = "npm run build"

[site]
bucket = "dist"

# Pages configuration
pages_build_output_dir = "dist/assets"

# Optional: If you have environment variables you need
# [vars]
# MY_VARIABLE = "someValue"
