[pages]
name = "galeriadecorruptos"
build_command = "npm run build"
build_directory = "dist"
pages_build_output_dir = "dist"
deploy_hook = ""

[build]
command = "npm run build"

[site]
bucket = "dist"

# Optional: If you have environment variables you need
# [vars]
# MY_VARIABLE = "someValue"
